### ISSUE TITLE
Add options for `covr::codecov()`

### ISSUE THREAD

**Issue by rubak** [eddelbuettel/r-ci#3]
I would like to run `covr::codecov(type = "all")` on a package. Would you be willing to support that? I don't know the best way to do this so I won't make a pull request before I hear your opinion. It may be that it is easier that I simply add a few lines to my yml to run it manually rather than you accommodating it here. Let me know what you think.

**Comment by eddelbuettel** [comment]
I am doing it in a number of packages. It is "less expensive" because using BSPM we get `covr` and its tail of dependencie easily.

See for example `anytime` (which I often default to as it comes early in the alphabetical sorting...) which has adds a block

```yaml
      - name: Coverage       
        if: ${{ matrix.os == 'ubuntu-latest' }}           
        run: ./run.sh coverage      
``` 

So ... it is already supported but maybe underdocumented.  Where would have have looked for documentation?
